# need super auth
sudo: required
# Tell Travis we need a copy of docker running
services:
  - docker
# Build our image using Dockerfile.dev
before_install:
  - docker build -t ns7137/docker-react -f Dockerfile.dev .
# Tell Travis how to run our test suite
script:
  - docker run ns7137/docker-react npm run test -- --coverage
# Tell travis how to deploy our code to AWS
deploy:
  provider: elasticbeanstalk
  # Docker-env.qbtbvwcxmh.us-west-2.elasticbeanstalk.com
  region: 'us-west-2'
  app: 'docker'
  env: 'Docker-env'
  # S3
  bucket_name: 'elasticbeanstalk-us-west-2-306476627547'
  bucket_path: 'docker'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: '$AWS_SECRET_KEY'
